# Adds a "Sponsor" button to the Rayo repository.
ko_fi: motunrayogbadebo
# Add your Paystack Payment Page link here once created (uncomment the line):
# custom: ["https://paystack.com/pay/your-slug"]
